/**
 * YKS (TYT & AYT) Ders ve Konu Başlıkları Veritabanı
 * Bu veritabanı, Kaan ve Çağan'ın konu bazlı ilerlemelerini ve eksiklerini takip etmek için kullanılır.
 */
const YKS_TOPICS = {
  TYT: {
    "Türkçe": [
      "Sözcükte Anlam",
      "Cümlede Anlam",
      "Paragrafta Anlam",
      "Ses Bilgisi",
      "Yazım Kuralları",
      "Noktalama İşaretleri",
      "Sözcükte Yapı",
      "İsimler (Adlar)",
      "Sıfatlar (Ön Adlar)",
      "Zamirler (Adıllar)",
      "Zarflar (Belirteçler)",
      "Edat - Bağlaç - Ünlem",
      "Fiiller (Eylemler) & Ek Fiil",
      "Fiilimsiler (Eylemsiler)",
      "Cümlenin Ögeleri",
      "Fiilde Çatı",
      "Cümle Türleri",
      "Anlatım Bozuklukları"
    ],
    "Matematik": [
      "Temel Kavramlar & Sayı Kümeleri",
      "Sayı Basamakları",
      "Bölme ve Bölünebilme Kuralları",
      "Asal Çarpanlara Ayırma & EBOB-EKOK",
      "Rasyonel & Ondalık Sayılar",
      "Birinci Dereceden Denklemler",
      "Basit Eşitsizlikler",
      "Mutlak Değer",
      "Üslü Sayılar",
      "Köklü Sayılar",
      "Çarpanlara Ayırma",
      "Oran-Orantı",
      "Sayı & Kesir Problemleri",
      "Yaş Problemleri",
      "İşçi Problemleri",
      "Hareket (Hız) Problemleri",
      "Yüzde, Kar-Zarar & Faiz Problemleri",
      "Karışım Problemleri",
      "Grafik Problemleri",
      "Rutin Olmayan Problemler",
      "Mantık",
      "Kümeler & Kartezyen Çarpım",
      "Fonksiyonlar (Temel)",
      "Permütasyon & Kombinasyon",
      "Binom Açılımı & Olasılık",
      "Veri & İstatistik"
    ],
    "Geometri": [
      "Doğruda ve Üçgende Açılar",
      "Özel Üçgenler (Dik, İkizkenar, Eşkenar)",
      "Üçgende Kenarortay, Açıortay ve Yükseklik",
      "Üçgende Eşlik ve Benzerlik",
      "Üçgende Alan",
      "Çokgenler ve Dörtgenler",
      "Paralelkenar, Eşkenar Dörtgen, Deltoid",
      "Yamuk",
      "Dikdörtgen & Kare",
      "Çemberde Açı ve Uzunluk",
      "Dairede Çevre ve Alan",
      "Katı Cisimler (Prizma, Piramit, Koni, Küre)",
      "Doğrunun Analitik İncelenmesi (Temel)"
    ],
    "Fizik": [
      "Fizik Bilimine Giriş",
      "Madde ve Özellikleri",
      "Hareket ve Kuvvet",
      "İş, Güç ve Enerji",
      "Isı, Sıcaklık ve Genleşme",
      "Elektrostatik",
      "Elektrik Akımı ve Devreler",
      "Basınç",
      "Kaldırma Kuvveti",
      "Dalgalar (Yay, Su, Ses, Işık)",
      "Optik (Aydınlanma, Aynalar, Kırılma, Mercekler, Renk)"
    ],
    "Kimya": [
      "Kimya Bilimi",
      "Atom ve Periyodik Sistem",
      "Kimyasal Türler Arası Etkileşimler",
      "Maddenin Halleri",
      "Doğa ve Kimya",
      "Kimyanın Temel Kanunları & Kimyasal Hesaplamalar",
      "Karışımlar",
      "Asitler, Bazlar ve Tuzlar",
      "Kimya Her Yerde"
    ],
    "Biyoloji": [
      "Canlıların Ortak Özellikleri",
      "Canlıların Yapısındaki Temel Bileşikler",
      "Hücrenin Yapısı ve Organeller",
      "Hücre Zarından Madde Geçişleri",
      "Canlıların Çeşitliliği ve Sınıflandırılması",
      "Hücre Bölünmeleri (Mitoz & Mayoz)",
      "Kalıtım og Soyağaçları",
      "Ekosistem Ekolojisi & Güncel Çevre Sorunları"
    ],
    "Tarih": [
      "Tarih ve Zaman",
      "İnsanlığın İlk Dönemleri",
      "Orta Çağ’da Dünya",
      "İlk ve Orta Çağlarda Türk Dünyası",
      "İslam Medeniyetinin Doğuşu ve İlk İslam Devletleri",
      "İlk Türk İslam Devletleri",
      "Yerleşme ve Devletleşme Sürecinde Selçuklu Türkiyesi",
      "Beylikten Devlete Osmanlı Siyaseti (1302-1453)",
      "Dünya Gücü Osmanlı (1453-1595)",
      "Yeni Çağ ve Yakın Çağ Avrupası",
      "Değişim Çağında Avrupa ve Osmanlı",
      "Uluslararası İlişkilerde Denge Stratejisi (1774-1914)",
      "XX. Yüzyıl Başlarında Osmanlı Devleti ve Dünya",
      "Milli Mücadele Hazırlık Dönemi & Genelgeler",
      "Birinci TBMM Dönemi & Kurtuluş Savaşı Cepheleri",
      "Atatürk İlke ve İnkılapları",
      "Atatürk Dönemi Türk Dış Politikası"
    ],
    "Coğrafya": [
      "Doğa ve İnsan Coğrafyası",
      "Dünya'nın Şekli ve Hareketleri",
      "Coğrafi Koordinat Sistemi & Yerel Saat",
      "Harita Bilgisi & İzohipsler",
      "Atmosfer ve Sıcaklık",
      "Basınç ve Rüzgarlar",
      "Nem ve Yağış",
      "Dünya'nın İklim Tipleri",
      "Dünya'nın Tektonik Yapısı ve İç Kuvvetler",
      "Dış Kuvvetler (Akarsu, Karstik, Rüzgar, Buzul, Dalga)",
      "Türkiye'nin Yeryüzü Şekilleri",
      "Yeryüzündeki Doğal Kaynaklar (Su, Toprak, Bitki)",
      "Nüfus Özellikleri, Dağılışı ve Piramitleri",
      "Türkiye'de Nüfus ve Göç",
      "Bölgeler ve Ülkeler Coğrafyası",
      "Afetler Coğrafyası"
    ],
    "Felsefe & Din": [
      "Felsefe ile Tanışma",
      "Bilgi Felsefesi (Epistemoloji)",
      "Varlık Felsefesi (Ontoloji)",
      "Ahlak Felsefesi (Etik)",
      "Sanat Felsefesi (Estetik)",
      "Din Felsefesi",
      "Siyaset Felsefesi",
      "Bilim Felsefesi",
      "İslam ve İbadet (Din Kültürü)",
      "Ahlak ve Değerler (Din Kültürü)",
      "Hz. Muhammed'in Hayatı ve Örnekliği",
      "İslam Düşüncesinde Yorumlar ve Mezhepler",
      "Kur'an ve Yorumu"
    ]
  },
  AYT: {
    "Matematik": [
      "Fonksiyonlarda Uygulamalar (Eksenleri Kesme, Artan-Azalan, Max-Min)",
      "Fonksiyon Dönüşümleri (Öteleme, Simetri)",
      "İkinci Dereceden Denklemler & Karmaşık Sayılar",
      "Parabol (İkinci Dereceden Fonksiyonlar)",
      "İkinci Dereceden Eşitsizlikler ve Eşitsizlik Sistemleri",
      "Polinomlar & Polinom Denklemleri",
      "Trigonometri I (Yönlü Açılar, Trigonometrik Oranlar, Özdeşlikler)",
      "Trigonometri II (Toplam-Fark, Yarım Açı, Trigonometrik Denklemler)",
      "Logaritma Fonksiyonu ve Özellikleri",
      "Logaritmalı Denklemler ve Eşitsizlikler",
      "Aritmetik & Geometrik Diziler",
      "Limit ve Süreklilik kavramı",
      "Türev Alma Kuralları",
      "Türevin Geometrik Yorumu & Teğet Denklemi",
      "Türevin Fiziksel Uygulamaları & Maksimum-Minimum Problemleri",
      "Belirsiz İntegral ve integral Alma Kuralları",
      "Belirli İntegral & Riemann Toplamı",
      "İntegral ile Alan Hesabı"
    ],
    "Geometri": [
      "Noktanın ve Doğrunun Analitik İncelenmesi (Detaylı)",
      "Çemberin Analitik İncelenmesi",
      "Dönüşüm Geometrisi (Öteleme, Dönme, Simetri)",
      "Katı Cisimlerin İleri Analizi ve Hacim Formülleri"
    ],
    "Fizik": [
      "Vektörler & Bağıl Hareket",
      "Newton’ın Hareket Yasaları (Sürtünme, Eylemsizlik)",
      "Bir Boyutta Sabit İvmeli Hareket (Atışlar)",
      "İki Boyutta Hareket (Yatay ve Eğik Atış)",
      "İş, Enerji ve Güç Teoremleri",
      "İtme ve Çizgisel Momentum Korunumu & Çarpışmalar",
      "Tork, Denge ve Kütle Merkezi",
      "Basit Makineler (Kaldıraç, Makara, Palanga, Eğik Düzlem vb.)",
      "Elektriksel Kuvvet (Coulomb Yasası) ve Elektriksel Alan",
      "Elektriksel Potansiyel Enerji ve Potansiyel Farkı",
      "Düzgün Elektriksel Alan (Paralel Levhalar) ve Sığaçlar (Kondansatör)",
      "Manyetik Alan, Manyetik Kuvvet ve Tork",
      "Elektromanyetik İndüklenme, Özindüksiyon ve Alternatif Akım",
      "Transformatörler",
      "Düzgün Çembersel Hareket & Merkezcil Kuvvet",
      "Dönerek Öteleme Hareketi & Açısal Momentum",
      "Kütleçekim Kuvveti, Kepler Yasaları ve Uydu Hareketi",
      "Basit Harmonik Hareket (Yay ve Basit Sarkaç)",
      "Dalga Mekaniği (Kırınım, Girişim, Doppler Efekti)",
      "Elektromanyetik Dalgalar ve Özellikleri",
      "Atom Modellerinin Tarihsel Gelişimi & Atom Fiziği",
      "Büyük Patlama ve Radyoaktivite (Alfa, Beta, Gama Işımaları)",
      "Özel Görelilik (Zaman Genişlemesi, Boy Kısalması)",
      "Kuantum Fiziğine Giriş (Kara Cisim Işıması, Fotoelektrik, Compton)",
      "Modern Fiziğin Teknolojideki Uygulamaları (Yarı İletkenler, X-Işınları, Görüntüleme)"
    ],
    "Kimya": [
      "Atomun Kuantum Modeli & Elektron Dizilimleri",
      "Periyodik Özellikler (Elektron ilgisi, Elektronegatiflik, Atom Yarıçapı)",
      "Gaz Yasaları, Kinetik Teori ve Gaz Karışımları",
      "Çözücü-Çözünen Etkileşimleri & Derişim Birimleri (Molarite, Molalite)",
      "Koligatif Özellikler (Kaynama Noktası Yükselmesi, Donma Noktası Alçalması)",
      "Çözünürlük ve Çözünürlüğe Etki Eden Faktörler",
      "Kimyasal Tepkimelerde Standart Oluşum Entalpileri & Tepkime Isısı",
      "Hess Yasası ve Bağ Enerjileri",
      "Tepkime Hızları, Hız Bağıntısı ve Hızı Etkileyen Faktörler",
      "Kimyasal Denge, Denge Sabiti (Kc, Kp) ve Le Chatelier İlkesi",
      "Asit-Baz Dengesi (pH, pOH, Zayıf Asit-Bazlar, Tampon Çözeltiler)",
      "Tuzların Çözünürlük Dengesi (Kç) & Ortak İyon Etkisi",
      "Redoks Tepkimeleri ve İndirgenme-Yükseltgenme Potansiyelleri",
      "Elektrokimyasal Hücreler (Galvanik Piller, Derişim Piller)",
      "Elektroliz, Faraday Kanunları ve Korozyon",
      "Karbon Kimyasına Giriş, Hibritleşme ve Molekül Geometrileri",
      "Hidrokarbonlar (Alkanlar, Alkenler, Alkinler, Arenler)",
      "Fonksiyonel Gruplar (Alkoller, Eterler, Karbonil Bileşikleri)",
      "Karboksilli Asitler ve Esterler",
      "Enerji Kaynakları ve Sürdürülebilirlik"
    ],
    "Biyoloji": [
      "Sinir Sistemi (İmpuls İletimi, Beyin Bölümleri)",
      "Endokrin Sistem (Hormonlar ve Salgı Bezleri)",
      "Duyu Organları (Göz, Kulak, Deri vb. Yapısı)",
      "Destek ve Hareket Sistemi (Kemik, Kıkırdak, Kas Kasılması)",
      "Sindirim Sistemi (Organlar, Enzimler ve Emilim)",
      "Dolaşım Sistemi (Kalp, Damarlar, Kan Hücreleri)",
      "Lenf Sistemi & Bağışıklık (Savunma Hatları)",
      "Solunum Sistemi (Gaz Alışverişi, Hemoglobin)",
      "Üriner (Boşaltım) Sistemi (Böbrek Yapısı, Nefronlar)",
      "Üreme Sistemi ve Embriyonik Gelişim",
      "Popülasyon Ekolojisi (Yaş Dağılımları, Büyüme Eğrileri)",
      "Komünite Ekolojisi (Rekabet, Av-Avcı, Simbiyotik İlişkiler)",
      "Nükleik Asitler (DNA & RNA Yapısı ve Keşfi)",
      "DNA Replikasyonu & Protein Sentezi (Transkripsiyon, Translasyon)",
      "Hücresel Solunum (Glikoliz, Krebs Döngüsü, ETS)",
      "Fotosentez (Işığa Bağımlı ve Bağımsız Evreler)",
      "Kemosentez",
      "Bitkisel Dokular ve Organlar (Kök, Gövde, Yaprak)",
      "Bitkilerde Madde Taşınması (Ksilem, Floem, Kohezyon-Gerilim)",
      "Bitkilerde Büyüme, Hareket (Tropizma, Nasti) ve Çiçek Yapısı",
      "Canlılar ve Çevre İlişkişi (Doğal Seçilim, Adaptasyon)"
    ],
    "Edebiyat": [
      "Güzel Sanatlar ve Edebiyatın Sınıflandırılması",
      "Coşku ve Heyecanı Dile Getiren Metinler (Şiir Bilgisi)",
      "Edebi Sanatlar (Söz Sanatları)",
      "Olay Çevresinde Oluşan Edebi Metinler (Tiyatro, Hikaye, Roman)",
      "İslamiyet Öncesi Türk Edebiyatı & Sözlü-Yazılı Dönem",
      "Geçiş Dönemi Eserleri (Kutadgu Bilig, Divanü Lugati't-Türk vb.)",
      "Halk Edebiyatı (Anonim, Aşık ve Tekke Edebiyatı)",
      "Divan Edebiyatı (Nazım Şekilleri, Türleri ve Sanatçıları)",
      "Tanzimat Dönemi Türk Edebiyatı (I. ve II. Dönem Özellikleri)",
      "Servet-i Fünun & Fecr-i Ati Edebiyatı",
      "Milli Edebiyat Dönemi Özellikleri ve Temsilcileri",
      "Cumhuriyet Dönemi Şiir Grupları (Yedi Meşaleciler, Garip, İkinci Yeni vb.)",
      "Cumhuriyet Dönemi Roman ve Hikaye Eğilimleri (Toplumcu Gerçekçi vb.)",
      "Edebi Akımlar (Klasisizm, Romantizm, Realizm vb.) ve Dünya Edebiyatı"
    ],
    "Tarih (AYT)": [
      "Tarih Bilimi ve İlk Uygarlıklar",
      "İlk Türk Devletleri ve Kültür Medeniyeti",
      "İslam Tarihi ve Medeniyeti",
      "Türk-İslam Tarihi (Karahanlı, Gazneli, Büyük Selçuklu)",
      "Türkiye Tarihi (Anadolu Beylikleri ve Selçuklular)",
      "Osmanlı Devleti Kuruluş ve Yükselme Dönemleri",
      "Osmanlı Devleti Kültür ve Teşkilatı",
      "Yeni ve Yakın Çağda Avrupa Gelişmeleri",
      "Osmanlı Devleti Arayış, Değişim ve Denge Dönemleri",
      "XX. Yüzyıl Başlarında Osmanlı Devleti",
      "I. Dünya Savaşı ve Sonuçları",
      "Milli Mücadele Hazırlık Çalışmaları",
      "Kurtuluş Savaşı Cepheleri ve Antlaşmalar",
      "Atatürk İlke ve İnkılapları",
      "Atatürk Dönemi Türk Dış Politikası",
      "Çağdaş Türk ve Dünya Tarihi (İkinci Dünya Savaşı, Soğuk Savaş)"
    ],
    "Coğrafya (AYT)": [
      "Biyoçeşitlilik, Ekosistemin Unsuru ve Enerji Akışı",
      "Madde Döngüleri (Karbon, Azot, Su Döngüsü)",
      "Ülkelerin Nüfus Politikaları (Çin, Rusya, Türkiye vb.)",
      "Şehirlerin Fonksiyonları ve Etki Alanları",
      "Türkiye'de Yerleşmeler ve Kentsel Dönüşüm",
      "Doğal Kaynaklar ve Ekonomi İlişkisi",
      "Türkiye'de Tarım, Hayvancılık ve Ormancılık",
      "Türkiye'nin Madenleri ve Enerji Kaynakları",
      "Türkiye'de Sanayi, Ulaşım, Ticaret ve Turizm",
      "Bölgesel Kalkınma Projeleri (GAP, DAP, DOKAP, ZBK)",
      "Küresel ve Bölgesel Örgütler (BM, NATO, AB, OPEC)",
      "Çevre Sorunlarının Türleri ve Küresel Çevre Sözleşmeleri",
      "Doğal Kaynakların Sürdürülebilir Kullanımı"
    ]
  }
};
